[[bodypart]]
name = "SpiderFlesh"
max_health = 3
move_bonus = 0
damage = 0
base = true
sprite_idx = 0
pivot = [0.0, 0.0]
connections = [[-1, 0], [1, 0], [0, 1], [0, -1]]

[[bodypart]]
name = "SpiderHead"
max_health = 2
move_bonus = 0
damage = 2
base = false
sprite_idx = 1
pivot = [0.0, 0.0]
connections = [[0, -1]]

[[bodypart]]
name = "SpiderLeg"
max_health = 2
move_bonus = 3
damage = 0
base = false
sprite_idx = 2
pivot = [0.0, 0.0]
connections = [[0, -1]]

[[bodypart]]
name = "SpiderCore"
max_health = 5
move_bonus = 0
damage = 1
base = true
sprite_idx = 3
pivot = [0.0, 0.0]
connections = [[-1, 0], [1, 0], [0, 1], [0, -1]]


[[bodypart]]
name = "CockroachFlesh"
max_health = 4
move_bonus = 0
damage = 0
base = true
sprite_idx = 4
pivot = [0.0, 0.0]
connections = [[-1, 0], [1, 0], [0, 1], [0, -1]]

[[bodypart]]
name = "CockroachHead"
max_health = 3
move_bonus = 0
damage = 1
base = false
sprite_idx = 5
pivot = [0.0, 0.0]
connections = [[0, -1]]

[[bodypart]]
name = "CockroachWings"
max_health = 3
move_bonus = 5
damage = 0
base = false
sprite_idx = 6
pivot = [0.0, 0.0]
connections = [[0, -1]]

[[bodypart]]
name = "CockroachCore"
max_health = 7
move_bonus = 1
damage = 0
base = true
sprite_idx = 7
pivot = [0.0, 0.0]
connections = [[-1, 0], [1, 0], [0, 1], [0, -1]]
