title = "04"

[[spawn_scene]]
t_sec = 0.1
name = "test"

[[dialogue]]
mode = { WaitSeconds = 3.0 }
name = "spindarella"
text = "are you some kind of scientist then? you said 'specimen' earlier"

[[dialogue]]
mode = { WaitSeconds = 4.0 }
name = "silkarella"
text = "yeah, I'm trying to figure out what's causing all these monsters to pop up in this cave"

[[dialogue]]
mode = { WaitSeconds = 2.0 }
name = "spindarella"
text = "do you enjoy it? being a scientist I mean"

[[dialogue]]
mode = { WaitSeconds = 5.0 }
name = "silkarella"
text = "It's not all bad, I did meet you from doing this hehe... Going to formal conferences to share results sucks though"

[[dialogue]]
mode = { WaitSeconds = 4.0 }
name = "spindarella"
text = "On the bright side I'm sure you look pretty good in a suit at those conferences"

[[dialogue]]
mode = { WaitSeconds = 5.0 }
name = "silkarella"
text = "You should come with me to one when this is over and find out for yourself"

transition = { AppState = "Game" }
