title = "05"

[[spawn_scene]]
spawn_on_dialogue = 0
name = "test"

[[dialogue]]
name = ""
text = ""

[[dialogue]]
name = "spindarella"
text = "So... how did you know my name?"

[[dialogue]]
name = "silkarella"
text = "What do you mean? You told me it when we met"

[[dialogue]]
name = "spindarella"
text = "Oh.. are you sure? I don't remember that"

[[dialogue]]
name = "silkarella"
text = "Yeah of course. How else would I have know it?"

[[dialogue]]
name = "spindarella"
text = "I suppose so yeah. What do you think of it, I chose it myself :D"

[[dialogue]]
name = "silkarella"
text = "Oh its a wonderful name, fits you well spindy"

transition = { AppState = "Game" }
